### ISSUE TITLE
Alien 0.1: durable local-first alias management

### ISSUE THREAD

**Issue by nickdonnelly** [nickdonnelly/alien#1]
## Problem Statement

Alien has grown from a fast way to capture the previous shell command into an alias manager with shell import, UFOs, sync, usage analytics, history tools, chaining, diagnostics, and agent integration. Its strongest workflow is useful, but the product boundary and contracts around state, synchronization, compatibility, recovery, and supported behavior are not yet coherent enough for a trustworthy 0.1 release.

An advanced shell user needs Alien to remain immediate and local-first while behaving predictably across Bash, Zsh, macOS, Linux, and multiple synchronized machines. They must be able to distinguish shared aliases from machine-local overrides, resolve conflicts without losing commands, recover from malformed or migrated state, install untrusted UFOs deliberately, and automate supported commands without depending on terminal interfaces. Existing user data must survive upgrades indefinitely.

The current implementation does not satisfy that contract. Shared and local state are not fully layered, sync exposes Git-level behavior instead of semantic conflicts, configuration parsing can silently accept or discard data, persisted JSON fails as a whole, release version injection is ineffective, and documentation promises some behavior that the program does not implement.

## Solution

Ship Alien 0.1 as an alias manager for advanced individual users, with team sharing as a secondary use case. Its defining promise is to turn the previous shell command into a reusable alias immediately.

Support capture, listing, editing, removal, execution, search, Bash and Zsh integration, shell import, UFO management, Git-backed sync, and command chaining. Keep fzf as the current picker behind a replaceable boundary. Keep analytics, doctor, history scanning, and agent-skill installation visible but experimental.

Separate synchronized shared state from machine-local overrides. Derive effective state by validating shared data, applying local overrides, and regenerating machine-local shell files and indexes. Sync only shared aliases, shared configuration, and installed UFO records. Keep credentials, usage, generated state, locks, and sync preferences local.

Make state durable through lossless parsing, semantic validation, ordered migrations, atomic writes, five retained snapshots, and explicit restoration. Resolve sync conflicts per alias or preference, not through raw conflict markers. Preserve native aliases and treat platform requirements as advisory. Warn before capturing likely secrets and keep confirmed secrets local unless the user explicitly promotes them.

## User Stories

1. As an advanced shell user, I want to capture my previous command under a name immediately, so that useful commands become reusable without editing shell files.
2. As a Bash user, I want capture to preserve supported command syntax, so that the saved alias behaves like the command I entered.
3. As a Zsh user, I want the same supported capture workflow as Bash, so that my shell choice does not make Alien unreliable.
4. As a shell user, I want pipelines to survive capture, so that multi-stage commands remain useful aliases.
5. As a shell user, I want multiline commands to survive capture, so that formatting does not corrupt their behavior.
6. As a shell user, I want quoted arguments and expansions to survive capture, so that the alias executes the intended command.
7. As a shell user, I want shell functions and shell-specific syntax identified correctly, so that Alien does not claim false portability.
8. As a remote-system user, I want Alien to capture the local command that starts an SSH session, so that ordinary local history remains consistent.
9. As a security-conscious user, I want Alien to detect common secret patterns before saving, so that credentials do not enter persistent state accidentally.
10. As an interactive user, I want to confirm a suspected secret, so that false positives do not block legitimate aliases.
11. As an automation author, I want noninteractive secret capture to fail without an explicit override, so that scripts cannot leak secrets silently.
12. As a user who confirms a suspected secret, I want it stored as a local override by default, so that synchronization does not publish it.
13. As a user who deliberately shares a sensitive command, I want a second explicit promotion action and plaintext warning, so that the consequence is unmistakable.
14. As a user who reviewed a command, I want Alien to remember that exact review, so that unchanged commands do not prompt repeatedly.
15. As a user who changes a reviewed command, I want Alien to review it again, so that approval does not apply to new content.
16. As a user encountering an existing alias name, I want to see both shared and local definitions, so that I understand what will change.
17. As a user resolving a name collision, I want to update shared state, update my local override, choose another name, rename the existing alias, or cancel, so that Alien never chooses for me.
18. As a user renaming an alias, I want the option to retain a deprecated forwarding name, so that scripts do not break immediately.
19. As a shell user, I want Alien to generate native aliases, so that aliases remain fast, inspectable, and directly callable.
20. As a user with an unmet alias requirement, I want search results to identify it, so that failures are understandable before invocation.
21. As an advanced user, I want direct invocation of an alias with unmet advisory requirements to remain possible, so that Alien does not overrule my environment knowledge.
22. As a cross-shell user, I want a shared command with optional Bash and Zsh variants, so that one logical alias can behave correctly in both shells.
23. As a user sharing aliases, I want shared names restricted to portable syntax, so that synchronized names work in supported shells.
24. As a user with a shell-specific local alias, I want broader validated naming rules, so that portability rules do not constrain private behavior needlessly.
25. As an fzf user, I want the existing picker behavior preserved for 0.1, so that a UI rewrite does not delay or destabilize the release.
26. As a future picker maintainer, I want picker actions and results independent of fzf, so that a native interface can replace it without changing behavior.
27. As a user building a chain, I want to select history entries in order, so that I can turn a repeated sequence into one alias.
28. As a user building a chain, I want to reorder, edit, and remove selected commands, so that one-off history details do not become permanent.
29. As a user building a chain, I want to see the exact command joined with conditional `&&` execution, so that I can verify it before saving.
30. As a user building a chain, I want `cd` and `export` effects to carry into later commands, so that grouping does not change the intended shell state.
31. As a user building a complex chain, I want redirection, multiline input, alternatives, and backgrounding grouped safely, so that composition preserves meaning where possible.
32. As a user building a chain, I want every component and the final command checked for secrets, so that composition cannot bypass capture safeguards.
33. As a user building a chain, I want Alien to save but never execute it during creation, so that reviewing an alias cannot trigger side effects.
34. As a UFO user, I want `alien ufo` to be canonical while `alien pack` remains an alias, so that terminology is consistent without breaking existing habits.
35. As a UFO user, I want installed versions pinned, so that shared commands do not change silently.
36. As a UFO user, I want updates to show added, changed, removed, and requirement-modified aliases, so that I can review their effect.
37. As a UFO user, I want to choose a version for update or rollback, so that changes remain deliberate and recoverable.
38. As a remote UFO user, I want the source, alias count, replacements, and checksum state shown before installation, so that I can assess trust.
39. As an interactive UFO user, I want to override a missing checksum explicitly, so that trusted ad hoc sources remain usable.
40. As an automation author, I want remote UFO installation to require a checksum, so that unattended downloads cannot bypass integrity checks.
41. As a UFO user, I want plain HTTP called out prominently, so that transport tampering risk is visible.
42. As a user who modified an UFO alias, I want my definition preserved as a local override during updates, so that upstream changes cannot erase my work.
43. As a team UFO consumer, I want the installed collection treated as read-only, so that local edits are not confused with upstream changes.
44. As a user installing an UFO with unmet requirements, I want to confirm the warning and retain direct invocation, so that metadata remains advisory.
45. As a local-only user, I want Alien to avoid Git and network behavior until I run `alien sync init`, so that sync is genuinely optional.
46. As a sync user, I want shared aliases, shared configuration, and UFO records synchronized, so that two machines behave alike by default.
47. As a sync user, I want local overrides, usage, generated state, locks, credentials, and sync settings excluded, so that machine-specific state stays private.
48. As a multi-machine user, I want separate shared and local files, so that I can inspect and reason about precedence.
49. As a user inspecting effective state, I want to see whether each value came from shared state or a local override, so that machine differences are apparent.
50. As a user with a redundant local override, I want Alien to remove it after notice, so that it cannot hide later shared changes.
51. As a user with a useful local override, I want to promote it into shared state through the CLI, so that other machines can receive it deliberately.
52. As a sync user, I want manual synchronization to be the default, so that Git operations do not surprise or block my shell.
53. As a sync user, I want optional pull-on-shell-start, push-after-mutation, or combined modes, so that I can choose an automation level.
54. As a sync user, I want Alien to attach to a remote I provide, so that it does not create hosting accounts or repositories for me.
55. As a security-conscious sync user, I want authentication delegated to Git, SSH agents, credential helpers, or keychains, so that Alien never stores credentials.
56. As a user initializing sync with existing local and remote state, I want nonconflicting entries merged, so that neither side is replaced wholesale.
57. As a user facing a sync conflict, I want to see the exact competing definitions and provenance, so that I can choose knowingly.
58. As a user resolving a sync conflict, I want to keep the remote value everywhere, publish my local value everywhere, keep my value only on this machine, rename a value, or abort, so that every resolution is explicit.
59. As a user encountering an automatic-sync conflict, I want Alien to stop and notify me instead of opening a prompt during shell startup, so that my shell remains usable.
60. As a user returning to a stopped sync, I want an explicit resolution command, so that I can resume safely.
61. As a user whose pull, migration, validation, or generation fails, I want my previous working effective state untouched, so that synchronization cannot break my shell.
62. As a long-term user, I want every future release to read historical Alien data, so that upgrading never abandons my aliases.
63. As a user whose data is migrated, I want a recoverable snapshot created first, so that I can undo a bad upgrade.
64. As a user making repeated changes, I want Alien to retain the five newest snapshots, so that recovery is useful without unbounded storage.
65. As a user diagnosing state, I want doctor to report available snapshots, so that I know recovery options exist.
66. As a user recovering state, I want a dedicated atomic restore command, so that restoration does not require manual file surgery.
67. As a user who manually edits strict JSON incorrectly, I want the exact syntax location reported while my last generated aliases remain active, so that one typo does not break my shell.
68. As a user with invalid individual entries in valid JSON, I want valid entries loaded and every rejected entry explained, so that one bad alias does not hide the rest.
69. As a user with invalid entries, I want Alien to preserve their raw data during later writes, so that partial loading does not become data loss.
70. As a user moving between versions, I want unknown fields preserved, so that an older writer does not erase newer metadata.
71. As a user editing configuration, I want conforming TOML parsing and validation, so that invalid values are not accepted silently.
72. As a user editing configuration, I want comments and unknown keys preserved by CLI mutations, so that Alien does not erase my work.
73. As a user who prefers direct editing, I want a nearby README and CLI warnings explaining validation and recovery, so that the risks are concrete.
74. As a terminal user, I want readable human output by default, so that routine commands are easy to understand.
75. As an automation author, I want selected commands to expose stable `--json` output, so that scripts do not parse terminal decoration.
76. As an automation author, I want supported commands to work without a TTY or fail with exact instructions, so that they never hang by opening a picker unexpectedly.
77. As a keyboard user, I want every supported interactive flow operable without a mouse, so that the terminal UI remains accessible.
78. As a terminal user, I want resize, narrow-window, cancellation, and `NO_COLOR` behavior, so that supported interfaces work in real terminals.
79. As a macOS user, I want Alien officially supported and tested, so that installation and shell integration are dependable.
80. As a Linux user, I want Alien officially supported and tested, so that installation and shell integration are dependable.
81. As a release user, I want the binary to report the version from its Git tag, so that diagnostics identify what I installed.
82. As a development-build user, I want the binary to identify itself as development or report its commit, so that it cannot masquerade as a release.
83. As an installer, I want release binaries, the install script, `go install`, and Homebrew treated as supported paths, so that each documented route works.
84. As a Homebrew user, I want correct repository metadata and dependency behavior, so that the formula installs the intended project.
85. As a privacy-conscious user, I want usage and history data to remain local unless I explicitly publish state, so that Alien does not become telemetry software.
86. As a maintainer, I want supported and experimental commands labeled clearly, so that compatibility promises are honest.
87. As a maintainer, I want renamed CLI commands retained for two minor releases, so that users have time to migrate.
88. As a maintainer, I want release-critical behavior protected by regression tests without a numeric coverage gate, so that tests follow risk rather than a percentage.
89. As a contributor, I want the README focused on installation and first use, so that detailed contracts do not bury onboarding.
90. As a contributor, I want sync, UFO, persistence, migration, security, compatibility, and troubleshooting references separated, so that each contract has a durable home.
91. As a maintainer, I want demo assets generated through one documented workflow, so that tracked sources and outputs are unambiguous.

## Implementation Decisions

- Keep Alien as one product context and use the canonical domain terms Alias, Shared alias, Local override, Effective state, UFO, UFO provenance, Chain, Requirement, Generated state, and Sync.
- Favor advanced individual users when personal and team behavior conflict. Model team sharing through read-only UFOs rather than making personal capture team-governed.
- Treat capture, shell integration, import, UFOs, sync, search, native aliases, fzf, and chains as supported 0.1 behavior. Keep analytics, doctor, history scanning, and agent-skill installation experimental.
- Preserve native Bash and Zsh aliases. Do not replace invocation with wrappers merely to enforce advisory requirements.
- Represent one logical alias with a shared definition, optional shell-specific definitions, provenance, validation status, and an optional local override.
- Store shared state and machine-local overrides in separate files. Compute Effective state by overlaying validated local values on validated shared state.
- Synchronize shared aliases, shared configuration, and UFO installation records. Never synchronize local overrides, Generated state, usage, locks, credentials, or sync preferences.
- Remove redundant local overrides after notice. Provide a CLI operation that promotes a local override into shared state.
- Preserve persisted user data through ordered, indefinite migrations. Create a snapshot before upgrade and retain the latest five snapshots.
- Separate document parsing from entry validation. A syntax error blocks mutations and keeps the last Generated state active. Invalid entries in a valid document are excluded with diagnostics but preserved losslessly.
- Preserve unknown persisted fields across reads and writes, including when an older Alien version writes newer data.
- Replace permissive configuration parsing with conforming TOML parsing. Validate recognized values on load and preserve comments and unknown keys during CLI changes.
- Validate the full candidate state before activation. Sync, migration, merge, persistence, and generation form one recoverable state transition.
- Keep Sync optional and manual by default. Model manual, pull-on-shell-start, push-after-mutation, and combined modes. Do not add a periodic daemon.
- Keep Git as the first transport behind Alien-owned commands. Alien may initialize local Git state or attach to a user-provided remote, but it does not create hosted repositories or store credentials.
- Resolve initial and later conflicts semantically per Alias or preference. Supported outcomes are remote shared, local published as shared, machine-local override, rename, and abort.
- Stop automatic sync on conflicts and direct the user to an explicit resolution command. Never start an interactive conflict interface during shell initialization.
- Treat likely-secret detection as a capture and promotion guard. Interactive users confirm; noninteractive callers require an explicit override; confirmed values stay local by default; explicit promotion warns that shared data is plaintext.
- Store a reviewed fingerprint for a suspected-secret command. A content change invalidates the review. Configurable detector rules are not part of 0.1.
- Preserve Bash and Zsh parity where possible. Document and test differences forced by each shell. Shared names use portable syntax; local or shell-specific names may use broader validated syntax.
- Compose Chains from ordered history entries with conditional `&&` behavior. Complex grouping must preserve same-shell state. Show and edit the exact command before saving, and never execute during creation.
- Make `ufo` canonical terminology and keep `pack` as a command alias. Internal identifiers may remain unchanged when renaming does not improve clarity.
- Pin UFO versions and require explicit updates. Store source, version, checksum, original definitions, and installed names as UFO provenance.
- Show semantic UFO diffs before update. Preserve user changes as Local overrides. Treat team UFOs as read-only for consumers.
- Require a checksum for noninteractive remote UFO installation. Interactive use may override a missing checksum explicitly. Warn on plain HTTP.
- Keep fzf for 0.1 while extracting picker inputs, actions, and results behind a testable internal boundary.
- Default to readable terminal output. Add stable JSON selectively for list, show, doctor, sync status, and ufo list where those commands have clear automation use.
- Require explicit noninteractive behavior for supported commands. Supported interactive flows handle keyboard use, resizing, narrow terminals, cancellation without mutation, `NO_COLOR`, and plain-text errors.
- Support macOS and Linux. Windows is not a current target.
- Source release versions from Git tags and distinguish development builds. Change version storage so linker injection can work, because the current constant ignores release linker flags.
- Support release binaries, the install script, `go install`, and the existing Homebrew formula. Correct repository metadata and verify fzf dependency behavior.
- Perform targeted extraction around state, transactional sync, picker behavior, and chain composition. Do not undertake a general package rewrite for 0.1.
- Keep the README concise and move durable contracts into focused reference documents. Make demo generation reproducible with an explicit source-of-truth policy.

## Testing Decisions

- Judge behavior at the highest practical external seam. Do not assert private helper structure or require a numeric coverage percentage.
- Use the CLI process seam as the primary test boundary. Run a built Alien binary against temporary Alien homes, Git repositories, history fixtures, and persisted-state fixtures. Assert exit status, terminal or JSON output, resulting shared and local state, recovery artifacts, and Generated state.
- Use real Bash and Zsh session tests only for behavior the CLI process seam cannot prove. Cover capture, native alias expansion, regeneration, same-shell Chain state, quoting, pipelines, multiline commands, functions, and shell-specific definitions.
- Use a release artifact seam for version injection, archives, install routes, and Homebrew packaging. Assert that a tagged build reports its tag and a development build cannot report a release version.
- Test state layering through Effective state behavior rather than internal map composition. The same fixture should prove precedence, provenance display, redundant-override cleanup, and Generated state.
- Test migrations with immutable fixtures from every historical schema version. Assert backup-before-upgrade, ordered migration, unknown-field preservation, and failure without mutation.
- Test malformed persistence in two categories: whole-document syntax failures and entry-level semantic failures. Assert exact diagnostics, warning status, continued access to valid entries, preservation of rejected raw entries, and continued availability of the last Generated state.
- Test transactional Sync with temporary local Git repositories. Cover initial merge, every conflict choice, abort, interruption, resume, automatic-mode notification, and failures during pull, migration, validation, persistence, and generation.
- Test secret handling at capture, Chain creation, noninteractive use, reviewed fingerprints, local default storage, and explicit shared promotion.
- Test UFO behavior at the command boundary with built-in, local-file, HTTPS fixture, plain-HTTP, checksum mismatch, missing-checksum, version update, rollback, conflict, and user-modification scenarios.
- Test picker-independent actions through the extracted action/result boundary. Retain focused manual smoke tests for real fzf rendering and terminal interaction.
- Test stable JSON as an API contract with golden or structural fixtures. Test human output for meaning and required diagnostics without coupling to decorative formatting.
- Test cancellation at every interactive mutation boundary and assert that no persisted or Generated state changed.
- Reuse the repository's existing command tests, store migration fixtures, locking tests, config tests, shell-hook tests, UFO and HTTP tests, local-Git sync tests, usage tests, scan tests, and UTF-8 formatting tests as prior art.
- Keep manual release smoke tests for real terminal rendering, fzf actions, Bash and Zsh startup, install scripts, release archives, and Homebrew on supported systems.

## Out of Scope

- Capturing commands typed inside a remote shell. Record a later design ticket covering remote installation, authentication, destination selection, offline behavior, sync interaction, and secret handling.
- Replacing fzf with a native picker. 0.1 creates the boundary only.
- Rich Requirement metadata and its full warning interface. The 0.1 schema may reserve room, but broad platform, executable, and environment modeling comes later.
- Multiple namespaced team UFO repositories, golinks-style discovery, and qualified team-to-team collision handling. 0.1 stabilizes existing UFOs and provenance.
- Periodic background synchronization or a daemon.
- A centralized UFO registry or hosted Alien sync service.
- Hosting-provider repository creation or credential storage.
- Windows support.
- Configurable secret detectors.
- Machine-to-machine copying of Local overrides outside shared promotion.
- A general rewrite of the existing Go package structure.

## Further Notes

- The agreed 0.1 release bar requires supported capture, import, UFO, Sync, and Chain behavior to match this specification; persistence and conflict behavior to avoid silent data loss; documentation to match implementation; release-critical regression tests; Bash and Zsh smoke tests on macOS and Linux; working CI and race tests; verified release packaging and Homebrew publication; and reproducible demo generation.
- The current worktree contains active README and demo work. The README describes configuration synchronization that is not implemented yet and also contains a `config.json` reference even though the program uses TOML. Reconcile documentation only when the corresponding behavior is implemented.
- The current release configuration attempts to inject a tag-derived version, but the application stores its version in a constant. A local verification showed that the linker flag succeeds without changing the reported `0.1.0` value. This is a confirmed release defect.
- Existing local HTTP tests may be unable to bind loopback sockets in restricted sandboxes. Treat that as an execution-environment limitation, not a product failure, while keeping the test in normal CI.
- The full implementation should follow dependency order: safe state foundations, shared/local layering, transactional Sync, capture and Chain hardening, UFO stability, interface contracts, release tooling, and documentation cleanup.
